import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Montserrat, Open_Sans } from "next/font/google";
import ScrollToTopBtn from "@/components/ScrollToTopBtn";

export const montserrat = Montserrat({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-montserrat",
});
export const opensans = Open_Sans({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-opensans",
});

export const metadata: Metadata = {
    title: "Extensão Adm Canindé",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="pt-BR" className={`h-full antialiased`}>
            <body className="min-h-full flex flex-col justify-between text-white leading-normal">
                <Header />
                <main className="flex-1 flex p-8">{children}</main>
                <Footer />
                <ScrollToTopBtn/>
            </body>
        </html>
    );
}
