import type { Metadata } from "next";
import "./globals.css";
import { Montserrat, Open_Sans } from "next/font/google";
import Providers from "./providers";

export const montserrat = Montserrat({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-montserrat",
});
export const opensans = Open_Sans({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-opensans",
});

export const metadata: Metadata = {
    title: "Projetos de Extensão FECISC do Curso de Administração",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="pt-BR"
            className="scroll-smooth antialiased"
            data-scroll-behavior="smooth"
        >
            <body className="text-white leading-normal min-h-dvh flex flex-col bg-neutral-900">
                <Providers>
                    <main className="flex flex-1">{children}</main>
                </Providers>
            </body>
        </html>
    );
}
