import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Login - Admin",
    description: "Generated by create next app",
};

export default function LoginPageLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return <main className="bg-mauve-800 flex justify-center pt-20">{children}</main>;
}
