import Footer from "@/components/Footer";
import Header from "@/components/Header";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Projetos de Extensão FECISC do Curso de Administração",
    description: "Generated by create next app",
};

export default function MainPageLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <main className="flex-1 flex flex-col">
            <Header />
            <main className="lg:p-16 px-4 py-8 flex-1">{children}</main>
            <Footer />
        </main>
    );
}
