import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Admin - Dashboard",
    description: "Generated by create next app",
};

export default function AdminPageLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return <>{ children }</>;
}
